export const OPPONENT_DAMAGE = 'OPPONENT DAMAGE';
export const PLAYER_DAMAGE = 'PLAYER DAMAGE';
export const OPPONENT_DRAIN = 'OPPONENT DRAIN';
export const SET_RANDOM_POKEMON = 'RANDOM';
export const ATTACK_INFO = 'ATTACK INFO';
export const EFFECT_ATTACK = 'EFFECT ATTACK';
export const ITEM_USE = 'ITEM USE';
